# Generated by Django 4.1.7 on 2023-03-01 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day_number',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='workout',
            name='day',
            field=models.ForeignKey(default='1.1', on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='workout_app.day'),
        ),
    ]
