# Generated by Django 4.1.7 on 2023-03-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0005_alter_day_day_number_alter_workout_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='max_backsquat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_cleanjerk',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_frontsquat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_snatch',
            field=models.IntegerField(default=0),
        ),
    ]
