# Generated by Django 4.1.7 on 2023-03-01 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0006_alter_profile_max_backsquat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='weights',
            field=models.IntegerField(choices=[(1, 'LB'), (2, 'KG')], default=1),
        ),
    ]
