# Generated by Django 4.1.7 on 2023-03-02 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0007_alter_profile_weights'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='username',
        ),
    ]
