# Generated by Django 4.1.7 on 2023-03-02 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0008_rename_user_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
