# Generated by Django 4.1.7 on 2023-03-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0009_rename_username_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='max_backsquat',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_cleanjerk',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_frontsquat',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_snatch',
            field=models.IntegerField(null=True),
        ),
    ]
